# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/CMakeFiles /workspace//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mysql_replicater

# Build rule for target.
mysql_replicater: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mysql_replicater
.PHONY : mysql_replicater

# fast build rule for target.
mysql_replicater/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/mysql_replicater.dir/build.make src/CMakeFiles/mysql_replicater.dir/build
.PHONY : mysql_replicater/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f src/common/CMakeFiles/common.dir/build.make src/common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named config

# Build rule for target.
config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 config
.PHONY : config

# fast build rule for target.
config/fast:
	$(MAKE) $(MAKESILENT) -f src/common/libconfig/lib/CMakeFiles/config.dir/build.make src/common/libconfig/lib/CMakeFiles/config.dir/build
.PHONY : config/fast

#=============================================================================
# Target rules for targets named config++

# Build rule for target.
config++: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 config++
.PHONY : config++

# fast build rule for target.
config++/fast:
	$(MAKE) $(MAKESILENT) -f src/common/libconfig/lib/CMakeFiles/config++.dir/build.make src/common/libconfig/lib/CMakeFiles/config++.dir/build
.PHONY : config++/fast

#=============================================================================
# Target rules for targets named c_example1

# Build rule for target.
c_example1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c_example1
.PHONY : c_example1

# fast build rule for target.
c_example1/fast:
	$(MAKE) $(MAKESILENT) -f src/common/libconfig/examples/c/CMakeFiles/c_example1.dir/build.make src/common/libconfig/examples/c/CMakeFiles/c_example1.dir/build
.PHONY : c_example1/fast

#=============================================================================
# Target rules for targets named c_example2

# Build rule for target.
c_example2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c_example2
.PHONY : c_example2

# fast build rule for target.
c_example2/fast:
	$(MAKE) $(MAKESILENT) -f src/common/libconfig/examples/c/CMakeFiles/c_example2.dir/build.make src/common/libconfig/examples/c/CMakeFiles/c_example2.dir/build
.PHONY : c_example2/fast

#=============================================================================
# Target rules for targets named c_example3

# Build rule for target.
c_example3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c_example3
.PHONY : c_example3

# fast build rule for target.
c_example3/fast:
	$(MAKE) $(MAKESILENT) -f src/common/libconfig/examples/c/CMakeFiles/c_example3.dir/build.make src/common/libconfig/examples/c/CMakeFiles/c_example3.dir/build
.PHONY : c_example3/fast

#=============================================================================
# Target rules for targets named c++_example1

# Build rule for target.
c++_example1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c++_example1
.PHONY : c++_example1

# fast build rule for target.
c++_example1/fast:
	$(MAKE) $(MAKESILENT) -f src/common/libconfig/examples/c++/CMakeFiles/c++_example1.dir/build.make src/common/libconfig/examples/c++/CMakeFiles/c++_example1.dir/build
.PHONY : c++_example1/fast

#=============================================================================
# Target rules for targets named c++_example2

# Build rule for target.
c++_example2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c++_example2
.PHONY : c++_example2

# fast build rule for target.
c++_example2/fast:
	$(MAKE) $(MAKESILENT) -f src/common/libconfig/examples/c++/CMakeFiles/c++_example2.dir/build.make src/common/libconfig/examples/c++/CMakeFiles/c++_example2.dir/build
.PHONY : c++_example2/fast

#=============================================================================
# Target rules for targets named c++_example3

# Build rule for target.
c++_example3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c++_example3
.PHONY : c++_example3

# fast build rule for target.
c++_example3/fast:
	$(MAKE) $(MAKESILENT) -f src/common/libconfig/examples/c++/CMakeFiles/c++_example3.dir/build.make src/common/libconfig/examples/c++/CMakeFiles/c++_example3.dir/build
.PHONY : c++_example3/fast

#=============================================================================
# Target rules for targets named c++_example4

# Build rule for target.
c++_example4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c++_example4
.PHONY : c++_example4

# fast build rule for target.
c++_example4/fast:
	$(MAKE) $(MAKESILENT) -f src/common/libconfig/examples/c++/CMakeFiles/c++_example4.dir/build.make src/common/libconfig/examples/c++/CMakeFiles/c++_example4.dir/build
.PHONY : c++_example4/fast

#=============================================================================
# Target rules for targets named libtinytest

# Build rule for target.
libtinytest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libtinytest
.PHONY : libtinytest

# fast build rule for target.
libtinytest/fast:
	$(MAKE) $(MAKESILENT) -f src/common/libconfig/tinytest/CMakeFiles/libtinytest.dir/build.make src/common/libconfig/tinytest/CMakeFiles/libtinytest.dir/build
.PHONY : libtinytest/fast

#=============================================================================
# Target rules for targets named libconfig_tests

# Build rule for target.
libconfig_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libconfig_tests
.PHONY : libconfig_tests

# fast build rule for target.
libconfig_tests/fast:
	$(MAKE) $(MAKESILENT) -f src/common/libconfig/tests/CMakeFiles/libconfig_tests.dir/build.make src/common/libconfig/tests/CMakeFiles/libconfig_tests.dir/build
.PHONY : libconfig_tests/fast

#=============================================================================
# Target rules for targets named ConFig

# Build rule for target.
ConFig: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ConFig
.PHONY : ConFig

# fast build rule for target.
ConFig/fast:
	$(MAKE) $(MAKESILENT) -f src/config/CMakeFiles/ConFig.dir/build.make src/config/CMakeFiles/ConFig.dir/build
.PHONY : ConFig/fast

#=============================================================================
# Target rules for targets named Net

# Build rule for target.
Net: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Net
.PHONY : Net

# fast build rule for target.
Net/fast:
	$(MAKE) $(MAKESILENT) -f src/net/CMakeFiles/Net.dir/build.make src/net/CMakeFiles/Net.dir/build
.PHONY : Net/fast

#=============================================================================
# Target rules for targets named Parser

# Build rule for target.
Parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Parser
.PHONY : Parser

# fast build rule for target.
Parser/fast:
	$(MAKE) $(MAKESILENT) -f src/parser/CMakeFiles/Parser.dir/build.make src/parser/CMakeFiles/Parser.dir/build
.PHONY : Parser/fast

#=============================================================================
# Target rules for targets named Process

# Build rule for target.
Process: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Process
.PHONY : Process

# fast build rule for target.
Process/fast:
	$(MAKE) $(MAKESILENT) -f src/process/CMakeFiles/Process.dir/build.make src/process/CMakeFiles/Process.dir/build
.PHONY : Process/fast

#=============================================================================
# Target rules for targets named access

# Build rule for target.
access: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 access
.PHONY : access

# fast build rule for target.
access/fast:
	$(MAKE) $(MAKESILENT) -f src/access/CMakeFiles/access.dir/build.make src/access/CMakeFiles/access.dir/build
.PHONY : access/fast

#=============================================================================
# Target rules for targets named tab1

# Build rule for target.
tab1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tab1
.PHONY : tab1

# fast build rule for target.
tab1/fast:
	$(MAKE) $(MAKESILENT) -f src/access/table/CMakeFiles/tab1.dir/build.make src/access/table/CMakeFiles/tab1.dir/build
.PHONY : tab1/fast

#=============================================================================
# Target rules for targets named acesscomm

# Build rule for target.
acesscomm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acesscomm
.PHONY : acesscomm

# fast build rule for target.
acesscomm/fast:
	$(MAKE) $(MAKESILENT) -f src/access/common/CMakeFiles/acesscomm.dir/build.make src/access/common/CMakeFiles/acesscomm.dir/build
.PHONY : acesscomm/fast

#=============================================================================
# Target rules for targets named index

# Build rule for target.
index: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 index
.PHONY : index

# fast build rule for target.
index/fast:
	$(MAKE) $(MAKESILENT) -f src/access/index/CMakeFiles/index.dir/build.make src/access/index/CMakeFiles/index.dir/build
.PHONY : index/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ConFig"
	@echo "... Net"
	@echo "... Parser"
	@echo "... Process"
	@echo "... access"
	@echo "... acesscomm"
	@echo "... c++_example1"
	@echo "... c++_example2"
	@echo "... c++_example3"
	@echo "... c++_example4"
	@echo "... c_example1"
	@echo "... c_example2"
	@echo "... c_example3"
	@echo "... common"
	@echo "... config"
	@echo "... config++"
	@echo "... index"
	@echo "... libconfig_tests"
	@echo "... libtinytest"
	@echo "... mysql_replicater"
	@echo "... tab1"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

